### ISSUE TITLE
Question: LOUD for Steam on Linux

### ISSUE THREAD

**Issue by feinmann** [LOUD-Project/Git-LOUD#31]
Hi there, thank you so much for your efforts improving FA. 

The thing is, I am running FA through Steam on Linux. Is there a chance to start the updater from Linux? Could you point me in the right direction, like should I use wine? I was not finding information on the forum.

Keep up the good work, kind regards

**Comment by TheRatCircus** [comment]
Thanks for the kind words.

At the moment, the updater client doesn't play nicely with Linux. I couldn't get it to run through WINE or Proton on my Linux Mint (Ubuntu 20.04). I attempted to build it for Linux myself and couldn't even setup the Electron toolchain due to a dependency on a deprecated library no longer supported on the Focal repository.

The best way to bypass this is by downloading the latest gamedata files from the [OneDrive](https://onedrive.live.com/?authkey=%21APAfOJusxNHJJWM&id=730910080073E6E6%214068&cid=730910080073E6E6). If you want to download custom maps, go to [the JSON manifest](https://theloudproject.org:8081/maps), and any map's `file` field can be appended to `https://theloudproject.org:8081/` to download that map's archive file.

Sorry that all of these workarounds are needed. The OneDrive isn't even always up-to-date because updating it isn't automated or even a formal part of the build pipeline. I will certainly try to make this happen in the near future, and eventually may retool the updater to be platform-agnostic.

**Comment by feinmann** [comment]
Thanks for prompt response.

Just to be clear: I understood to replace the `gamedata` folder in my local files (and only the `gamedata` folder) by the respective folder on the onedrive. I just did that and the game starts from steam, but then the menu appears unuseable. 

![Bildschirmfoto von 2021-03-19 11-35-28](https://user-images.githubusercontent.com/2109648/111768126-d0dd1d80-88a7-11eb-8ab4-6b796973ecea.png)

Kind regards

**Comment by TheRatCircus** [comment]
Sorry, I could have clarified better how to install from the OneDrive. The final directory structure should look like this:
```
Supreme Commander Forged Alliance
 |-> gamedata
 |-> LOUD
      |-> usermods
      |-> usermaps
      |-> bin (from OneDrive)
      |-> gamedata (from OneDrive)
      |-> etc.
```
Then run `steam -applaunch 9420 /log "Loud.log" /init "../LOUD/bin/LoudDataPath.lua"`. Make sure to create a new profile from within the mod; there's no compatibility with profiles created in the vanilla game or FAF.

**Comment by feinmann** [comment]
Thank you so much. Works perfekt. I had to download the standard-map. Seams very cool. I have to figure out the mods and so on. Hope this thread helps others on Linux.
